### ISSUE TITLE
QUESTION: using pageID for saving rm pages

### ISSUE THREAD

**Issue by martsec** [subutux/rmapy#17]
Hi, first a little bit of background: I am using this program as a first step to later do some analysis, and I realized there is a mismatch between how and what this program outputs (Zip Files) and the current reMarkable App way of saving the files in two ways: 

1. This program does not save any metadata file for the documents (although the information is partially there)
2.  The individual rm files are saved with the page number instead of the page ID. 

While I know that those two behaviors are similar in rmapi, I don't see the reasoning behind that, since we then have an incompatibility between the later programs that use the saved files by the official apps and the files from this application. However, since I've not used all the program functionalities, I could not say it for certain.

So, is there a reasoning behind having those two differences with the official app? 

Thanks

PS: I have the changes in code already done and I could contribute in case the output of the discussion is that is a good idea to follow the same approach as the official apps.

**Comment by subutux** [comment]
Hi Martsec,

Could you make a pull request so I can take a look at the code?
I Think you are referring to [this](https://github.com/subutux/rmapy/blob/50fef896d34897f798ba572ef86b685ebb72b3cb/rmapy/document.py#L258)?
