### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by chessnocow** [subutux/rmapy#18]
Hello, could you show a usage example? How to connect to API and upload a file.

with zipfile.ZipFile('test.zip', 'w') as myzip:
    myzip.write('test.pdf')
    client = api.Client()
    doczip = document.ZipDocument()
    doczip.zipfile = myzip
    client.upload(doczip, upload_folder)

Am I doing this right?

Thanks in advance for your answer.

**Comment by subutux** [comment]
Hi!

please check the QuickStart documentation. If there is something not clear enough, please let me know! 
https://rmapy.readthedocs.io/en/latest/quickstart.html
