### ISSUE TITLE
Any hint why the time are returning incorrect format?

### ISSUE THREAD

**Issue by espoirMur** [subutux/rmapy#20]
First of all, thanks for putting this; it is awesome. I want to contribute to the project. If there is something you will like to integrate, let me know I can hack it during my weekend.

So I was having [this issue](https://github.com/ddvk/remarkable-hacks/issues/250), and I couldn't figure out what was wrong with my device. But I used the API and found that all the documents I send to the device via the extension are mostly coming with the wrong date `0001-01-01T00:00:00Z` i don't know why. 

With this, I am not able to display the newly send content to the device. 

Do you have any workaround? Or point me to a solution?

### Step to reproduce :

With the chrome extension, try to send a document to your device via the chrome extension. 

With this code, you can see the document but with the wrong date. 

```
# create an API instance
collection = rmapy.get_meta_items()

docs = [ doc.to_dict() for doc in collection]
for doc in docs:
    doc["ModifiedClient"] = parser.parse(doc.get("ModifiedClient"))
    print(doc.get("VissibleName"),  doc.get("ModifiedClient"))   
```
For my side, I am getting the following documents : 

```
Meet Aiden, your new AI coworker – TechCrunch 0001-01-01T00:00:00Z
CENI: la religion énerve | Politico.cd 0001-01-01T00:00:00Z
Guide: How To Answer Chevening Scholarship Interview Questions - Cynthia Kimola 0001-01-01T00:00:00Z
wddIRHD-LiwIc_L0i7yNuPT5fNw (1).pdf 0001-01-01T00:00:00Z
```

**Comment by subutux** [comment]
I Don't know what this has to do with this python module.

I assume this has something to do with the way the Chrome extension works with timestamp and possible using the wrong format, or possibly that it has never been accessed before on the remarkable tablet, before using rmapy.

Better create an issue at the Chrome extension.


for what it's worth, this works on my end:

```python
from rmapy.api import Client
rm = Client()
rm.renew_token()
collection = rmapy.get_meta_items()
docs = [ doc.to_dict() for doc in collection]
d = docs[0]
d.to_dict().get("ModifiedClient")
# returns '2018-10-31T09:51:01.851851Z'
```

Closing, not reproducible
